name: Update Data

on:
  schedule:
    - cron: "0 12 * * *" # daily at 9:30 UTC
  workflow_dispatch: # allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      EIA_API_KEY: ${{ secrets.EIA_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run data update script
        run: poetry run update_data
        # env:
        #   PYTHONPATH: ${{ github.workspace }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/data/
          git commit -m "Update data ($(date -u))" || echo "No changes to commit"
          git push
