name: Update Data

on:
  schedule:
    - cron: "0 12 * * *" # daily at 12 UTC
  workflow_dispatch: # allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      EIA_API_KEY: ${{ secrets.EIA_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: make install

      - name: Run data update script
        run: make update

      - name: Commit updated JSON to GitHub Pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin gh-pages
          git switch gh-pages
          cp public/data/daily_energy_mix_latest.json data/daily_energy_mix_latest.json
          git add data/daily_energy_mix_latest.json
          git commit -m "Update data ($(date -u))" || echo "No changes"
          git push origin gh-pages
